### ISSUE TITLE
Assignment 3 Peer Review

### ISSUE THREAD

**Issue by SaelinB** [STAT547-UBC-2019-20/group_13#20]
1. Is the repository organized in a useful and sensible way?
* Yes, the repository makes sense and is easy to navigate, has milestone subsections in the readme and appropriate folders. 

2. Is there a Usage section in the README?
* Yes, there is a usage section that clearly explains what each script does, what folder to move to to run the scripts and the appropriate arguments. 

3. Do the scripts run to completion as described in the README?
* The usage says to navigate within the src folder first, but the scripts are written to run from outside that folder (‘scr/load_data.R’). 
*  From just copying and pasting the commands from the usage section they did not run, but that was because there was a space between “--” and “url_to_read”. After deleting the space, they ran. 
* process_data.R didn’t run because of mistake in argument – you specified suiciderates_clean.csv as the input, when you meant suiciderates.csv (I believe, from looking at the script). Using this, it works.
* EDA_script.csv runs
* Some comments: The milestone specified that process_data.R should have two arguments, which I took to mean the input file written by load_data.R, and the cleaned output file. You don't have to specify a URL for each argument, just the file paths to the file, e.g. in process_data.R input could just be "data/suiciderates.csv". Additionally, using the same URL for load_data and process_data makes load_data unnecessary - your process_data is now loading the data as well.

4. Do the scripts produce the expected output?
* Yes, the csv outputs and images look correct. 

5. Are the scripts and functions appropriately documented?
* The usage description is fine, but the description about what each script does could be more detailed, with description on the input, how the input changes and the output. 
* Author and dates are there
* Good using of commenting to describe what the code is doing
* Also, should probably follow the function documentation style that is shown in 18.3.3 of the guide (I didn't do this either)

6. Does it take a long time for the analyses to run? Are there tasks that could be vectorized to make things faster?
* No, scripts were fast and I don’t see any point where vectorization would be used to improve - except in process_data.R. I don't really understand why you divide the NA sums by 27820*12, but if you wanted to find number of NAs in each column you could've used seq_along(suiciderates) to do so in a vectorized way. Although this wouldn't make it any faster, it would a better way of showing that all the NAs come from that one column that you removed. 

Overall, good job.

**Comment by Farnaz1234** [comment]
Thanks SaelinB for your feedback on our milestone 3! I have addressed your comments below:

1. and 2. thank you! 
3. - Thanks for letting us know. We will try to change our usage section so in indicates that the 
       scripts will run from 'scr/load_data.R'
    - We fixed the space “--”
    - That's true, we used suiciderates_clean.csv as the input for process_data.R
    - Glad to hear that EDA_script.csv runs
    - Thanks for mentioning that. Yes, because this is a data analysis pipeline.
4. Great that csv outputs and images look good
5. - We will try to add more details to our descriptions for what each script does
    - Yes, we added author and date
    - Thanks, we try to provide comments to notify the reader what our code does
    - Good idea, maybe something to consider in future
6. I learned that we can use seq_along(suiciderates) to show that we removed a column which most 
    NA's of our dataset came from. We have 27820 observations and 12 variables.

**Comment by Farnaz1234** [comment]
Sorry, I don't know why the numbers turned out like that.
