### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by matthewconnell** [STAT547-UBC-2019-20/group_13#36]
Hi @racquellem and @Farnaz1234 

Did you end up getting the app to deploy on Heroku? The link in the readme (https://farrac-milestone6.herokuapp.com/) gives an application error.

**Comment by racquellem** [comment]
Hi Matthew,

Yes, I ended up being able to deploy the app on heroku: https://group13-suicides.herokuapp.com/. I will update the README now.

Thanks,
Racquelle
